package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Factory;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface FactoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FACTORY
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FACTORY
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    int insert(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FACTORY
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    Factory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FACTORY
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    List<Factory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FACTORY
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    int updateByPrimaryKey(Factory record);
}