package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Model;

public interface ModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODEL
     *
     * @mbg.generated Sun May 17 16:08:46 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODEL
     *
     * @mbg.generated Sun May 17 16:08:46 EEST 2020
     */
    int insert(Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODEL
     *
     * @mbg.generated Sun May 17 16:08:46 EEST 2020
     */
    Model selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODEL
     *
     * @mbg.generated Sun May 17 16:08:46 EEST 2020
     */
    List<Model> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODEL
     *
     * @mbg.generated Sun May 17 16:08:46 EEST 2020
     */
    int updateByPrimaryKey(Model record);
}