package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.ModelOwners;

public interface ModelOwnersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODEL_OWNERS
     *
     * @mbg.generated Sun May 17 16:08:46 EEST 2020
     */
    int insert(ModelOwners record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODEL_OWNERS
     *
     * @mbg.generated Sun May 17 16:08:46 EEST 2020
     */
    List<ModelOwners> selectAll();
}