package lt.vu.mybatis.model;

public class Factory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FACTORY.ID
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FACTORY.NAME
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FACTORY.ID
     *
     * @return the value of PUBLIC.FACTORY.ID
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FACTORY.ID
     *
     * @param id the value for PUBLIC.FACTORY.ID
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FACTORY.NAME
     *
     * @return the value of PUBLIC.FACTORY.NAME
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FACTORY.NAME
     *
     * @param name the value for PUBLIC.FACTORY.NAME
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}