package lt.vu.mybatis.model;

public class ModelOwners {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL_OWNERS.MODELS_ID
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    private Integer modelsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL_OWNERS.OWNERS_ID
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    private Integer ownersId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL_OWNERS.MODELS_ID
     *
     * @return the value of PUBLIC.MODEL_OWNERS.MODELS_ID
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    public Integer getModelsId() {
        return modelsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL_OWNERS.MODELS_ID
     *
     * @param modelsId the value for PUBLIC.MODEL_OWNERS.MODELS_ID
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    public void setModelsId(Integer modelsId) {
        this.modelsId = modelsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL_OWNERS.OWNERS_ID
     *
     * @return the value of PUBLIC.MODEL_OWNERS.OWNERS_ID
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    public Integer getOwnersId() {
        return ownersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL_OWNERS.OWNERS_ID
     *
     * @param ownersId the value for PUBLIC.MODEL_OWNERS.OWNERS_ID
     *
     * @mbg.generated Sun May 17 17:28:52 EEST 2020
     */
    public void setOwnersId(Integer ownersId) {
        this.ownersId = ownersId;
    }
}