package lt.vu.mybatis.model;

public class Model {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.ID
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.NAME
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.FACTORY_ID
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    private Integer factoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.ID
     *
     * @return the value of PUBLIC.MODEL.ID
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.ID
     *
     * @param id the value for PUBLIC.MODEL.ID
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.NAME
     *
     * @return the value of PUBLIC.MODEL.NAME
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.NAME
     *
     * @param name the value for PUBLIC.MODEL.NAME
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.FACTORY_ID
     *
     * @return the value of PUBLIC.MODEL.FACTORY_ID
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.FACTORY_ID
     *
     * @param factoryId the value for PUBLIC.MODEL.FACTORY_ID
     *
     * @mbg.generated Mon May 18 19:33:19 EEST 2020
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }
}